### ISSUE TITLE
stack trace from provision

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#275]
From version 1.0.6:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13edcd7]

goroutine 1 [running]:
github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision.(*provision).verifyCustomerProxy.func1(0xc0003241c0, 0x34, 0x0, 0x0)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision/provision.go:639 +0x167
github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision.(*provision).verifyCustomerProxy(0xc000121180, 0xc0002e43c0, 0x1519550, 0x1519540, 0x0, 0x0)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision/provision.go:648 +0x126
github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision.(*provision).run(0xc000121180, 0x1519550, 0x1519540)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision/provision.go:267 +0x379
github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision.Cmd.func2(0xc0000aaf00, 0xc00012a960, 0x0, 0xa)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/apigee-istio/cmd/provision/provision.go:107 +0x9d
github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000aaf00, 0xc00012a820, 0xa, 0xa, 0xc0000aaf00, 0xc00012a820)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aac80, 0x13f2d20, 0xc00001e240, 0xc0000aac80)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000aac80, 0xb, 0xb)
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /Users/theganyo/dev/istio/src/github.com/apigee/istio-mixer-adapter/apigee-istio/main.go:42 +0x8c
```

**Comment by theganyo** [comment]
The root cause was an expired certificate on the organization. However, the command should not have just stack dumped. Will resolve.
